# Generated by Django 5.0.7 on 2024-08-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_faq_requestor_staff_message_intent_message_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='response',
            new_name='encrypted_response',
        ),
        migrations.RemoveField(
            model_name='message',
            name='vector',
        ),
    ]
